### ISSUE TITLE
[ ! BUG ! ] Após o primeiro GET /Reserva ser feito, novos recursos criados em POST /reservas não são listados em uma nova consulta de GET /Reserva

### ISSUE THREAD

**Issue by nobruaraujo** [postechfiapgrupo04/stopcar#8]
## Description 

Após fazer uma consulta em GET /reservas são listados os recursos existentes, porém se for criado um novo recurso após esse GET, este novo recurso não é exibido. 
Somente os recursos listados na primeira consulta são exibidos.

## Expected behavior

Após criar um novo recurso POST, este deve ser listado, mesmo se uma consulta já tiver sido feita antes.

## Features affected

GET /reservas 

## Any screemshot

https://github.com/postechfiapgrupo04/stopcar/assets/156858009/801e8e37-3a15-45d2-9bc2-380ccb9db42d

**Comment by nobruaraujo** [comment]
Já foi visto que envolve o Cache da aplicação, pois esta base é atualizada depois de uns minutos.
Psc. @nassula

**Comment by nassula** [comment]
Esse não era um erro em si, mas sim aplicação de cache de 30min para atualizar essa rota.
